changelog check test

diff --git a/.github/workflows/merge.yaml b/.github/workflows/merge.yaml
--- a/.github/workflows/merge.yaml
+++ b/.github/workflows/merge.yaml
@@ -46,20 +46,30 @@ jobs:
 
             for i in {0..2}; do
               if [[ ${v1[i]:-0} -lt ${v2[i]:-0} ]]; then
-                echo "PROJECT_VERSION is higher :: [$1 < $2]"
-                echo "✅"
+                echo "✅  PROJECT_VERSION is higher :: [$1 < $2]"
                 return 0
               elif [[ ${v1[i]:-0} -gt ${v2[i]:-0} ]]; then
-                echo "LATEST_RELEASE is higher :: [$1 > $2]"
+                echo "⛔  LATEST_RELEASE is higher :: [$1 > $2]"
                 echo "⚠️  Double-check that you've pulled/merged the latest version before continuing." | tee -a $GITHUB_STEP_SUMMARY
                 echo "⛔  Project version [$2] needs to be higher than latest release [$1], please adjust the version in [OMC/Infrastructure/WebApi/EventsHandler/EventsHandler.csproj]" | tee -a $GITHUB_STEP_SUMMARY
                 return 2
               fi
             done
-            echo "Versions are equal :: [$1 == $2]"
+            echo "⚠️  Versions are equal :: [$1 == $2]"
             echo "⛔  Project version [$2] needs to be higher than latest release [$1], please adjust the version in [OMC/Infrastructure/WebApi/EventsHandler/EventsHandler.csproj]" | tee -a $GITHUB_STEP_SUMMARY
             return 1
           }
 
           compare_versions "${{ steps.release.outputs.version_release }}" "${{ steps.project.outputs.version_project }}"
         name: Check project and latest release versions
+        
+      - run: |
+          echo "Checking if the project version is listed in CHANGELOG.md"
+
+          if ! grep -q "## ${{ steps.project.outputs.version_project }}" CHANGELOG.md; then
+            echo "⛔  Version ${{ steps.project.outputs.version_project }} not found in CHANGELOG.md"
+            exit 1
+          else
+            echo "✅ Version ${{ steps.project.outputs.version_project }} found in CHANGELOG.md"
+          fi
+        name: Check if project version is in CHANGELOG.md
